### ISSUE TITLE
use pyheat for cgi

### ISSUE THREAD

**Issue by JeasonGong** [csurfer/pyheat#6] opened 2017-02-13 03:13 UTC
I watch the code,find pyheat can't be uesd for cgi

**Comment by csurfer** [comment] 2017-02-14 04:34
Please explain your issues in detail, possibly with a list of reproducible steps. That way it is easier for anyone looking at it to understand and work on it.

**Comment by csurfer** [comment] 2017-02-21 02:37
Closing this due to lack of information provided.

**Closed as completed by csurfer** 2017-02-21 02:37 UTC
